### ISSUE TITLE
sample_rate vs sampling_rate issue

### ISSUE THREAD

**Issue by kdoroschak** [nanoporetech/fast5_research#14]
https://github.com/nanoporetech/fast5_research/blob/ced32dc0314f9b1fd7bbada2ba8a62f1da1b0064/fast5_research/fast5.py#L89

This line currently raises an Attribute error if the channel_meta already contains `self.sample_rate` and does not contain `self.sampling_rate`.

Instead, it should probably just verify that `self.sample_rate` is present, and if not, look for `self.sampling_rate`.

Maybe something like this?

```
try:
    getattr(self, 'sample_rate')
except AttributeError:
    self.sample_rate = self.sampling_rate
```

**Comment by cjw85** [comment]
Yes, I can see how that might be a problem. I'm curious though how you have a file where `sample_rate` is in `channel_meta`. IIRC the value has never been recorded as such, and the backward compatibility note in the code is in reference to an older version of this API which had a typo.

**Comment by kdoroschak** [comment]
Ah interesting, didn't occur to me that it might be a typo. The sample_rate
attribute is from a bulk file (unsegmented fast5).

**Comment by cjw85** [comment]
If you're trying to access data in a bulk file, you'll want the class `BulkFast5` instead of `Fast5`.

**Comment by kdoroschak** [comment]
Thanks for pointing that out, not sure how I missed it. I use both bulk and
normal fast5s (including writing to normal fast5s) so this connects some
dots on my end as well.

Probably not worth making that change then. Thanks for your help & quick
response!

**Comment by cjw85** [comment]
No problem.
