### ISSUE TITLE
Writing fast5 problem

### ISSUE THREAD

**Issue by smaegol** [nanoporetech/fast5_research#24]
Hi, 

I'm trying to write some fast5 files and pass them later to Albacore for testing. However, when I use
```
with Fast5.New(filename, 'w', tracking_id=tracking_id, context_tags=context_tags, channel_id=channel_id) as h:
    h.set_raw(raw_data, meta=read_id, read_number=100)
```
(as in the example from documentation) resultant fast5 is not processed by Albacore (with the error `Could not extract read data from file`). I tried with the extracted data from the other fast5 file and the result was the same. However, when I tried with the ont-fast5-api, using the same parameters as in the previous example everything worked well when I added device_id and hostname keys to the tracking_id:
```
run_id = str(uuid4()).replace('-','')
tracking_id = {
    'exp_start_time': '1970-01-01T00:00:00Z',
    'run_id': run_id,
    'flow_cell_id': 'FAH00000',
    'device_id': 'MN00000',
    'hostname': 'hostname'
}

with Fast5Writer(self._path, 'writer_test1', 1, tracking_id = tracking_id) as writer:
    writer.write_strand(strand)
```
With the same tracking_id  fast5_research written file still fails with Albacore. The only difference I noticed is the writing of 3 keys values in tracking_id: flow_cell_id, exp_start_time and run_id, like below for flow_cell_id:
```
ATTRIBUTE "flow_cell_id" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;                                                                                                                                                                                          }
            DATASPACE  SCALAR
            DATA {
            (0): "b'FAH28257'"
            }
         }
```

As you can see string is written as a byte (b') and it probably shouldn't. Can this be the reason for problems with Albacore? Or the problem sits somewhere else?

**Comment by cjw85** [comment]
Hi @smaegol 
I believe this issue should be resolved by the above. Sorry for the inconvenience.

version 1.2.8 should appear on pypi shortly.
