### ISSUE TITLE
`DeprecationWarning` thrown when calling `np.asscalar(a)`

### ISSUE THREAD

**Issue by franrodalg** [nanoporetech/fast5_research#30]
Hi! Thanks for the library!

Currently, creating a new `Fast5File` object or calling `summary()` from a previously created one (and probably when using many other functions in the library), leads to the following:
`<PATH_TO_NUMPY>/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead`
being printed many times. 
The fix in the message should do it.
Cheers!

**Comment by cjw85** [comment]
Thanks for this.

A new version should appear on pypi shortly.
